branches:
    only:
        - master
language: php
jobs:
    include:
      - php: '5.2'
        dist: precise
      - php: '5.3'
        dist: precise
dist: trusty
    php:
        - hhvm-3.3
        - '7.0'
    
services:
    - docker    
install:
    - composer install
allow_failures:
    - php: '5.3'
    - php: '7.0'
    - php: hhvm    
script: phpunit --configuration phpunit.xml --coverage-txt
notifications:
    email: false