branches:
    only:
        - master
language: php
php:
    - '5.2'
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm
services:
    - docker    
before-install:
    - composer self-update
install:
    - composer install
allow_failures:
    - php: '5.3'
    - php: '5.6'
    - php: '7.0'
    - php: hhvm    
script: phpunit --configuration phpunit.xml --coverage-txt
notifications:
    email: false