branches:
    only:
        - master
language: php
jobs:
    include:
      - php: '5.3'
        dist: precise
services:
    - docker    

allow_failures:
    - php: '5.3'

script: phpunit --configuration phpunit.xml
notifications:
    email: false